/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.9
 * Generated at: 2017-04-24 02:33:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardmanagement_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1492046862470L));
    _jspx_dependants.put("/WEB-INF/views/navi/adminnavi.jsp", Long.valueOf(1492997071819L));
    _jspx_dependants.put("/WEB-INF/views/footer/footer.jsp", Long.valueOf(1492070914174L));
    _jspx_dependants.put("jar:file:/C:/spring_project/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/spring-final/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/navi/adminSidebar.jsp", Long.valueOf(1492997071817L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tvar ajaxFunction = function(universityCode) {\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype:'post',\r\n");
      out.write("\t\t\t\turl : '/jhta/admin/boardmanagement',\r\n");
      out.write("\t\t\t\tdata : universityCode,\r\n");
      out.write("\t\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\t$('#semester-select').empty();\r\n");
      out.write("\t\t\t\t\t$('#lecture-select').empty();\r\n");
      out.write("\t\t\t\t\t$.each(data.siteMapList, function(index, item){\r\n");
      out.write("\t\t\t\t\t\t$('#semester-select').append(\"<option value=\"+item.code+\">\"+item.name+\"</option>\");\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t$.each(data.lectureList, function(index, item){\r\n");
      out.write("\t\t\t\t\t\t$('#lecture-select').append(\"<option value=\"+item.no+\">\"+item.subjectName+\"</option>\");\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\tif (!data.lectureList) {\r\n");
      out.write("\t\t\t\t\t\t$('#lecture-select').append(\"<option>학과의 수업과정이 등록되어 있지 않습니다.</option>\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}  \r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar universityCode = $('#term-select').val();\r\n");
      out.write("\t\tajaxFunction(universityCode);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#term-select').change(function(){\r\n");
      out.write("\t\t\tuniversityCode = $(this).val();\r\n");
      out.write("\t\t\tajaxFunction(universityCode);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#semester-select').change(function(){\r\n");
      out.write("\t\tvar subjectCode = $(this).val();\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype:'post',\r\n");
      out.write("\t\t\t\turl: '/jhta/admin/boardmanagement.json',\r\n");
      out.write("\t\t\t\tdata : subjectCode,\r\n");
      out.write("\t\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\t$('#lecture-select').empty();\r\n");
      out.write("\t\t\t\t\t$.each(data, function(index, item){\r\n");
      out.write("\t\t\t\t\t\t$('#lecture-select').append(\"<option value=\"+item.no+\">\"+item.subjectName+\"</option>\");\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\tif (!data.length) {\r\n");
      out.write("\t\t\t\t\t\t$('#lecture-select').append(\"<option>학과의 수업과정이 등록되어 있지 않습니다.</option>\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$('#search-btn').click(function(){\r\n");
      out.write("\t\t\t$('#hidden-div').show();\r\n");
      out.write("\t\t\tvar lectureCode = $('#lecture-select').val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write(" <style type=\"text/css\">\r\n");
      out.write(" \r\n");
      out.write("@import url('//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css');\r\n");
      out.write("\r\n");
      out.write(".navbar-default .navbar-nav #user-profile {\r\n");
      out.write("    height: 50px;\r\n");
      out.write("    padding-top: 15px;\r\n");
      out.write("    padding-left: 58px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-default .navbar-nav #user-profile img {\r\n");
      out.write("    height: 45px;\r\n");
      out.write("    width: 45px;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 2px;\r\n");
      out.write("    left: 8px;\r\n");
      out.write("    padding: 1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#wrapper {\r\n");
      out.write("    padding-top: 50px;\r\n");
      out.write("    padding-left: 0;\r\n");
      out.write("    -webkit-transition: all .5s ease;\r\n");
      out.write("    -moz-transition: all .5s ease;\r\n");
      out.write("    -o-transition: all .5s ease;\r\n");
      out.write("    transition: all .5s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media (min-width: 992px) {\r\n");
      out.write("    #wrapper {\r\n");
      out.write("        padding-left: 225px;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media (min-width: 992px) {\r\n");
      out.write("    #wrapper #sidebar-wrapper {\r\n");
      out.write("        width: 225px;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar-wrapper {\r\n");
      out.write("    border-right: 1px solid #e7e7e7;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar-wrapper {\r\n");
      out.write("    z-index: 1000;\r\n");
      out.write("    position: fixed;\r\n");
      out.write("    left: 225px;\r\n");
      out.write("    width: 0;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    margin-left: -225px;\r\n");
      out.write("    overflow-y: auto;\r\n");
      out.write("    background: #f8f8f8;\r\n");
      out.write("    -webkit-transition: all .5s ease;\r\n");
      out.write("    -moz-transition: all .5s ease;\r\n");
      out.write("    -o-transition: all .5s ease;\r\n");
      out.write("    transition: all .5s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar-wrapper .sidebar-nav {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    width: 225px;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    list-style: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar-wrapper .sidebar-nav li {\r\n");
      out.write("    text-indent: 0;\r\n");
      out.write("    line-height: 45px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar-wrapper .sidebar-nav li a {\r\n");
      out.write("    display: block;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar-wrapper .sidebar-nav li a .sidebar-icon {\r\n");
      out.write("    width: 45px;\r\n");
      out.write("    height: 45px;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    padding: 0 2px;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    text-indent: 7px;\r\n");
      out.write("    margin-right: 10px;\r\n");
      out.write("    color: #000;\r\n");
      out.write("    float: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar-wrapper .sidebar-nav li a .caret {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  right: 23px;\r\n");
      out.write("  top: auto;\r\n");
      out.write("  margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar-wrapper .sidebar-nav li ul.panel-collapse {\r\n");
      out.write("    list-style: none;\r\n");
      out.write("    -moz-padding-start: 0;\r\n");
      out.write("    -webkit-padding-start: 0;\r\n");
      out.write("    -khtml-padding-start: 0;\r\n");
      out.write("    -o-padding-start: 0;\r\n");
      out.write("    padding-start: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar-wrapper .sidebar-nav li ul.panel-collapse li i {\r\n");
      out.write("    margin-right: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar-wrapper .sidebar-nav li ul.panel-collapse li {\r\n");
      out.write("    text-indent: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media (max-width: 992px) {\r\n");
      out.write("    #wrapper #sidebar-wrapper {\r\n");
      out.write("        width: 45px;\r\n");
      out.write("    }\r\n");
      out.write("    #wrapper #sidebar-wrapper #sidebar #sidemenu li ul {\r\n");
      out.write("        position: fixed;\r\n");
      out.write("        left: 45px;\r\n");
      out.write("        margin-top: -45px;\r\n");
      out.write("        z-index: 1000;\r\n");
      out.write("        width: 200px;\r\n");
      out.write("        height: 0;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar-nav li a {\r\n");
      out.write("    color: #fff !important;\r\n");
      out.write("}\r\n");
      out.write(".sidebar-nav li ul li a {\r\n");
      out.write("\tbackground-color: #fff !important;\r\n");
      out.write("\tcolor: #0077e5 !important;\t\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("    <div id=\"navbar-wrapper\">\r\n");
      out.write("        <header>\r\n");
      out.write("            <nav class=\"navbar navbar-default navbar-fixed-top\" role=\"navigation\" style=\"background-color: #4296dc;\">            \r\n");
      out.write("                <div class=\"container-fluid\">\r\n");
      out.write("                    <div class=\"navbar-header\">\r\n");
      out.write("                        <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#navbar-collapse\">\r\n");
      out.write("                            <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                            <span class=\"icon-bar\"></span>\r\n");
      out.write("                            <span class=\"icon-bar\"></span>\r\n");
      out.write("                            <span class=\"icon-bar\"></span>\r\n");
      out.write("                        </button>\r\n");
      out.write("                        <a class=\"navbar-brand\" href=\"home\" style=\"color: white;\"><span class=\"glyphicon glyphicon-education\"></span> JHTA 학사 관리 시스템</a>\r\n");
      out.write("                            <ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t\t      <li><a href=\"searchstud\" style=\"color: white;\">학적 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t      <li><a href=\"semester\" style=\"color: white;\">교과 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t      <li><a href=\"#\" style=\"color: white;\">수업 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t      <li><a href=\"#\" style=\"color: white;\">수강 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t      <li><a href=\"scorelist.do\" style=\"color: white;\">성적 관리</a></li>\r\n");
      out.write("    \t\t\t\t\t\t</ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div id=\"navbar-collapse\" class=\"collapse navbar-collapse\">\r\n");
      out.write("                        <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("                        \t<li><a id=\"user-profile\" href=\"#\"style=\"color: white;\"><img src=\"/jhta/resources/images/student/PeoPleDefault.png\" class=\"img-responsive img-thumbnail img-circle\"> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${LOGIN_USER.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("님 환영합니다.</a></li>\r\n");
      out.write("                            <li><a href=\"#\" style=\"color: white;\">내 정보 수정</a></li>\r\n");
      out.write("                            <li><a href=\"/jhta/logout\" style=\"color: white;\">로그아웃</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </header>\r\n");
      out.write("    </div>\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function() {\r\n");
      out.write("\t$(\"a.accordion-toggle\").click(function() {\t\r\n");
      out.write("\t$(\".panel-collapse\").not($(this)).attr(\"class\",\"panel-collapse panel-switch collapse\");\r\n");
      out.write("\t});\r\n");
      out.write("})\r\n");
      out.write("</script>\r\n");
      out.write("\t<div id=\"wrapper\">\r\n");
      out.write("        <div id=\"sidebar-wrapper\">\r\n");
      out.write("            <aside id=\"sidebar\">\r\n");
      out.write("                <ul id=\"sidemenu\" class=\"sidebar-nav\" style=\"background-color: #4296dc;\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"accordion-toggle collapsed toggle-switch\" data-toggle=\"collapse\" data-target=\"#submenu-2\">\r\n");
      out.write("                            <span class=\"sidebar-icon\"></span><span class=\"sidebar-title\">사용자 조회</span>\r\n");
      out.write("                            <b class=\"caret\"></b>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul id=\"submenu-2\" class=\"panel-collapse collapse panel-switch\" role=\"menu\">\r\n");
      out.write("                            <li><a href=\"#\"><i class=\"fa fa-caret-right\"></i>학생 정보 조회</a></li>\r\n");
      out.write("                            <li><a href=\"#\"><i class=\"fa fa-caret-right\"></i>교수 정보 조회</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"accordion-toggle collapsed toggle-switch\" data-toggle=\"collapse\" href=\"#submenu-3\">\r\n");
      out.write("                            <span class=\"sidebar-icon\"></span><span class=\"sidebar-title\">입학관리</span>\r\n");
      out.write("                            <b class=\"caret\"></b>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul id=\"submenu-3\" class=\"panel-collapse collapse panel-switch\" role=\"menu\">\r\n");
      out.write("                            <li><a href=\"#\"><i class=\"fa fa-caret-right\"></i>신입학 등록</a></li>\r\n");
      out.write("                            <li><a href=\"#\"><i class=\"fa fa-caret-right\"></i>신입학 조회</a></li>\r\n");
      out.write("                            <li><a href=\"#\"><i class=\"fa fa-caret-right\"></i>재입학 등록</a></li>\r\n");
      out.write("                            <li><a href=\"#\"><i class=\"fa fa-caret-right\"></i>재입학 조회</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"accordion-toggle collapsed toggle-switch\" data-toggle=\"collapse\" href=\"#submenu-4\">\r\n");
      out.write("                            <span class=\"sidebar-icon\"></span><span class=\"sidebar-title\">휴학 관리</span>\r\n");
      out.write("                            <b class=\"caret\"></b>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul id=\"submenu-4\" class=\"panel-collapse collapse panel-switch\" role=\"menu\">\r\n");
      out.write("                            <li><a href=\"#\"><i class=\"fa fa-caret-right\"></i>휴학 신청 목록</a></li>\r\n");
      out.write("                            <li><a href=\"#\"><i class=\"fa fa-caret-right\"></i>휴학 승인 목록</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"accordion-toggle collapsed toggle-switch\" data-toggle=\"collapse\" href=\"#submenu-5\">\r\n");
      out.write("                            <span class=\"sidebar-icon\"></span><span class=\"sidebar-title\">복학 관리</span>\r\n");
      out.write("                            <b class=\"caret\"></b>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul id=\"submenu-5\" class=\"panel-collapse collapse panel-switch\" role=\"menu\">\r\n");
      out.write("                            <li><a href=\"#\"><i class=\"fa fa-caret-right\"></i>복학 신청 목록</a></li>\r\n");
      out.write("                            <li><a href=\"#\"><i class=\"fa fa-caret-right\"></i>복학 승인 목록</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"accordion-toggle collapsed toggle-switch\" data-toggle=\"collapse\" href=\"#submenu-6\">\r\n");
      out.write("                            <span class=\"sidebar-icon\"></span><span class=\"sidebar-title\">전과 관리</span>\r\n");
      out.write("                            <b class=\"caret\"></b>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul id=\"submenu-6\" class=\"panel-collapse collapse panel-switch\" role=\"menu\">\r\n");
      out.write("                            <li><a href=\"#\"><i class=\"fa fa-caret-right\"></i>전체 전과 내역 조회</a></li>\r\n");
      out.write("                            <li><a href=\"#\"><i class=\"fa fa-caret-right\"></i>전과 신청 목록</a></li>\r\n");
      out.write("                            <li><a href=\"#\"><i class=\"fa fa-caret-right\"></i>전과 승인 목록</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"accordion-toggle collapsed toggle-switch\" data-toggle=\"collapse\" href=\"#submenu-7\">\r\n");
      out.write("                            <span class=\"sidebar-icon\"></span><span class=\"sidebar-title\">게시판 관리</span>\r\n");
      out.write("                            <b class=\"caret\"></b>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul id=\"submenu-7\" class=\"panel-collapse collapse panel-switch\" role=\"menu\">\r\n");
      out.write("                            <li><a href=\"boardmanagement\"><i class=\"fa fa-caret-right\"></i>강의 게시판 관리</a></li>\r\n");
      out.write("                            <li><a href=\"homeboard\"><i class=\"fa fa-caret-right\"></i>홈페이지 게시판 관리</a></li>\r\n");
      out.write("                            <li><a href=\"board\"><i class=\"fa fa-caret-right\"></i>전체 공지관리</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"accordion-toggle collapsed toggle-switch\" data-toggle=\"collapse\" href=\"#submenu-8\">\r\n");
      out.write("                            <span class=\"sidebar-icon\"></span><span class=\"sidebar-title\">자퇴 관리</span>\r\n");
      out.write("                            <b class=\"caret\"></b>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul id=\"submenu-8\" class=\"panel-collapse collapse panel-switch\" role=\"menu\">\r\n");
      out.write("                            <li><a href=\"#\"><i class=\"fa fa-caret-right\"></i>자퇴 신청 목록</a></li>\r\n");
      out.write("                            <li><a href=\"#\"><i class=\"fa fa-caret-right\"></i>자퇴 승인 목록</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"accordion-toggle collapsed toggle-switch\" data-toggle=\"collapse\" href=\"#submenu-9\">\r\n");
      out.write("                            <span class=\"sidebar-icon\"></span><span class=\"sidebar-title\">커뮤니티 관리</span>\r\n");
      out.write("                            <b class=\"caret\"></b>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul id=\"submenu-9\" class=\"panel-collapse collapse panel-switch\" role=\"menu\">\r\n");
      out.write("                            <li><a href=\"../adminrecmessagebox\"><i class=\"fa fa-caret-right\"></i>쪽지 관리</a></li>\r\n");
      out.write("                            <li><a href=\"#\"><i class=\"fa fa-caret-right\"></i>메일 관리</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </aside>            \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container\" style=\"margin-left: 250px; padding-top:25px;\">\r\n");
      out.write("\t\t<div class=\"row text-right\">\r\n");
      out.write("\t\t\t홈 > 학적관리 > 입학관리 > 신입학 조회 \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<h4><span class=\"glyphicon glyphicon-th-list\"></span> 게시판 관리</h4>\r\n");
      out.write("\t\t\t<hr style=\"border:solid 0.5px #2C7BB5;\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"margin-top: 20px;\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t<table class=\"table\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>대학선택</th>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<select id=\"term-select\" class=\"form-control\" style=\"width: 150px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<th>학과선택</th>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<select id=\"semester-select\" class=\"form-control\" style=\"width: 150px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>강좌선택</th>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t\t\t<select id=\"lecture-select\" class=\"form-control\" style=\"width: 430px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t<div class=\"row\" style=\"margin-top: 64px;\">\r\n");
      out.write("\t\t\t\t\t<button id=\"search-btn\" class=\"btn btn-primary btn-sm\">검색</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"hidden-div\" hidden=\"\">\r\n");
      out.write("\t\t\t<div class=\"row well\">\r\n");
      out.write("\t\t\t\t<strong>사본_NIE를 활용한 글쓰기 과정 /자유게시판: <span id=\"freeBoardCount\">0</span>건 /강의Q&amp;A: <span id=\"qnaBoardCount\">0</span>건 </strong>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav nav-tabs\" role=\"tablist\" id=\"myTab\">\r\n");
      out.write("\t\t\t\t\t<li role=\"presentation\" class=\"active\"><a href=\"#profile\" aria-controls=\"profile\" role=\"tab\" data-toggle=\"tab\">강의 Q&amp;A</a></li>\r\n");
      out.write("\t\t\t\t\t<li role=\"presentation\"><a href=\"#messages\" aria-controls=\"messages\" role=\"tab\" data-toggle=\"tab\">강의 공지사항</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"tab-content\" style=\"margin-top: 15px;\">\r\n");
      out.write("\t\t\t\t\t<div role=\"tabpanel\" class=\"tab-pane active\" id=\"profile\">\r\n");
      out.write("\t\t\t\t\t\t<form class=\"form-inline\">\r\n");
      out.write("\t\t\t\t\t\t\t<select class=\"form-contro input-sm\" name=\"searchCount\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"10\">10개 보기</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"30\">30개 보기</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"50\">50개 보기</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t<label> 총게시물 <span id=\"totalCount\">0</span>개, 검색 <span id=\"searchCount\">0</span>개</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group pull-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<select class=\"form-control input-sm\" name=\"searchKeywordBox\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"title\">제목</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"contents\">내용</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"name\">이름</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"id\">아이디</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"keyword\" class=\"form-control input-sm\" type=\"text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"btn btn-primary btn-sm\">검색</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t\t<table class=\"table\">\r\n");
      out.write("\t\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"5%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"*\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th><input type=\"checkbox\" id=\"allCheck\"/></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>제목</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>작성자</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>등록일</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-danger btn-sm\" id=\"delete-btn\">선택삭제</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div role=\"tabpanel\" class=\"tab-pane\" id=\"messages\">\r\n");
      out.write("\t\t\t\t\t\t<form class=\"form-inline\">\r\n");
      out.write("\t\t\t\t\t\t\t<select class=\"form-contro input-sm\" name=\"searchCount\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"10\">10개 보기</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"30\">30개 보기</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"50\">50개 보기</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t<label> 총게시물 <span id=\"totalCount\">0</span>개, 검색 <span id=\"searchCount\">0</span>개</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-group pull-right\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<select class=\"form-control input-sm\" name=\"searchKeywordBox\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"title\">제목</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"contents\">내용</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"name\">이름</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"id\">아이디</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input name=\"keyword\" class=\"form-control input-sm\" type=\"text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"btn btn-primary btn-sm\">검색</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t<hr>\r\n");
      out.write("\t\t\t\t\t\t<table class=\"table\">\r\n");
      out.write("\t\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"5%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"*\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th><input type=\"checkbox\" id=\"allCheck\"/></th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>제목</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>작성자</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>등록일</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-danger btn-sm\" id=\"delete-btn\">선택삭제</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("        \r\n");
      out.write("\t\t</div>\r\n");
      out.write("        <!-- /#page-wrapper -->\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /#wrapper -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/board/boardmanagement.jsp(95,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("major");
      // /WEB-INF/views/board/boardmanagement.jsp(95,8) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/board/boardmanagement.jsp(95,8) '${majorList }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${majorList }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${major.code }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${major.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("\t\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }
}
