/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.9
 * Generated at: 2017-04-26 02:43:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.student;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class stuMain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/views/navi/sidebarstud.jsp", Long.valueOf(1493173781356L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1492046862470L));
    _jspx_dependants.put("jar:file:/C:/spring_project/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/spring-final/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/spring_project/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/spring-final/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/navi/stunavi.jsp", Long.valueOf(1492392196499L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>\r\n");
      out.write("  <link href=\"../resources/fullcalendar/fullcalendar.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("  <link href=\"../resources/fullcalendar/fullcalendar.print.min.css\" rel=\"stylesheet\" media=\"print\" />\r\n");
      out.write("  <script src=\"../resources/fullcalendar/lib/moment.min.js\"></script>\r\n");
      out.write("  <script src=\"../resources/fullcalendar/lib/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"../resources/fullcalendar/fullcalendar.min.js\"></script>\r\n");
      out.write("  <style type=\"text/css\">\r\n");
      out.write("   th { \r\n");
      out.write("   \t  text-align: center !important;\r\n");
      out.write("      vertical-align: middle !important;\r\n");
      out.write("      }\r\n");
      out.write("   td{\r\n");
      out.write("   \t  text-align: center !important;\r\n");
      out.write("      vertical-align: middle !important;\r\n");
      out.write("   }\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function() {\r\n");
      out.write("\t\r\n");
      out.write("\t// 제목과 내용을 전달받아서 작은 모달창을 표시하기\r\n");
      out.write("\tfunction showSmallModal(title, message) {\r\n");
      out.write("\t\t$('#small-modal-title').text(title);\r\n");
      out.write("\t\t$(\"#small-modal-body\").html(\"<small>\" + message + \"</small>\");\r\n");
      out.write("\t\t$('#small-modal').modal('show');\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 모달창이 켜질 때 모달창의 값을 초기화한다.\r\n");
      out.write("\tfunction initializeForm(date) {\r\n");
      out.write("\t\tvar yyyymmdd = date.format();\r\n");
      out.write("\t\tvar now = new Date();\r\n");
      out.write("\t\tvar hour = now.getHours();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#event-form-modal #event-title\").val(\"\");\r\n");
      out.write("\t\t$(\"#event-form-modal #event-description\").val(\"\");\r\n");
      out.write("\t\t$(\"#event-form-modal #event-start-date\").val(yyyymmdd);\r\n");
      out.write("\t\t$(\"#event-form-modal #event-end-date\").val(yyyymmdd);\r\n");
      out.write("\t\t$(\"#event-form-modal #event-start-hour\").val(hour);\r\n");
      out.write("\t\t$(\"#event-form-modal #event-start-minute\").val(\"00\");\r\n");
      out.write("\t\t$(\"#event-form-modal #event-end-hour\").val(parseInt(hour)+1);\r\n");
      out.write("\t\t$(\"#event-form-modal #event-end-minute\").val(\"00\");\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 새로 등록할 일정정보를 모달창에서 읽어와서 객체로 만들기\r\n");
      out.write("\tfunction createEventData() {\r\n");
      out.write("\t\tvar eventData = {};\r\n");
      out.write("\t\teventData[\"title\"] = $(\"#event-title\").val();\r\n");
      out.write("\t\teventData[\"description\"] = $(\"#event-description\").val();\r\n");
      out.write("\t\teventData[\"startDate\"] = $('#event-start-date').val();\r\n");
      out.write("\t\teventData[\"startHour\"] = $('#event-start-hour').val();\r\n");
      out.write("\t\teventData[\"startMinute\"] = $('#event-start-minute').val();\r\n");
      out.write("\t\tif (!$(\"#event-all-day\").prop(\"checked\")) {\r\n");
      out.write("\t\t\teventData[\"endDate\"] = $('#event-end-date').val();\r\n");
      out.write("\t\t\teventData[\"endHour\"] = $('#event-end-hour').val();\r\n");
      out.write("\t\t\teventData[\"endMinute\"] = $('#event-end-minute').val();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\teventData[\"allDay\"] = $(\"#event-all-day\").prop(\"checked\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\treturn eventData;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 날짜에 대한 타임값을 YYYY-MM-DD HH:mm 형식을 문자열로 변환하기\r\n");
      out.write("\tfunction timeToString(time) {\r\n");
      out.write("\t\treturn moment(new Date(time)).format(\"YYYY-MM-DD HH:mm\");\r\n");
      out.write("\t}\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t// 새로운 일정정보를 등록하는 버튼을 클릭했을 때 실행된다.\r\n");
      out.write("\t$(\"#add-event-btn\").click(function() {\r\n");
      out.write("\t\tvar startDateBefore = new Date($('#event-start-date').val());\r\n");
      out.write("\t\tvar endDateBefore = new Date($('#event-end-date').val());\r\n");
      out.write("\t\tvar startDateAfter = startDateBefore.getTime() + $('#event-start-hour').val() + $('#event-start-minute').val() ;\r\n");
      out.write("\t\tvar endDateAfter = endDateBefore.getTime() + $('#event-end-hour').val() + $('#event-end-minute').val();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif($(\"#event-title\").val()== \"\") {\r\n");
      out.write("\t\t\talert(\"제목을 입력하세요\");\r\n");
      out.write("\t\t\t$(\"#event-title\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tif($(\"#event-description\").val()== \"\") {\r\n");
      out.write("\t\t\talert(\"내용을 입력하세요\");\r\n");
      out.write("\t\t\t$(\"#event-description\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(startDateAfter >= endDateAfter) {\r\n");
      out.write("\t\t\talert(\"종료 날짜가 시작 날짜 보다 먼저 일 수 없습니다.\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype:'post',\r\n");
      out.write("\t\t\t\turl:'addevent.do',\r\n");
      out.write("\t\t\t\tdataType:'json',\r\n");
      out.write("\t\t\t\tdata:createEventData(),\t\r\n");
      out.write("\t\t\t\tsuccess:function(data) {\r\n");
      out.write("\t\t\t\t\t$(\"#event-form-modal\").modal(\"hide\");\r\n");
      out.write("\t\t\t\t\t// 캘린더를 갱신한다.\r\n");
      out.write("\t\t\t\t\t$(\"#calendar-box\").fullCalendar( 'refetchEvents' );\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#delete-event-btn\").click(function() {\r\n");
      out.write("\t\tvar schNo = $(\"#event-no-detail\").val();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl:'deleteEvent.do',\r\n");
      out.write("\t\t\tdataType:'json',\r\n");
      out.write("\t\t\tdata:'schNo=' + schNo,\r\n");
      out.write("\t\t\tsuccess:function(data) {\r\n");
      out.write("\t\t\t\t$(\"#event-form-modal-detail\").modal(\"hide\");\r\n");
      out.write("\t\t\t\t// 캘린더를 갱신한다.\r\n");
      out.write("\t\t\t\t$(\"#calendar-box\").fullCalendar( 'refetchEvents' );\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("/* \t$(\"#edit-event-btn\").click(function() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t}); */\r\n");
      out.write("\t\r\n");
      out.write("\t// 캘린더를 초기화한다.\r\n");
      out.write("\t$(\"#calendar-box\").fullCalendar({\r\n");
      out.write("\t\t// [events : 일정데이트를 조회하는 콜백함수를 등록한다.]\r\n");
      out.write("\t\t// 콜백함수는 캘린더에서 년/월/주가 변경될 때마다 실행된다.\r\n");
      out.write("\t\t// 콜백함수는 start와 end는 moment함수다.\r\n");
      out.write("\t\t// start와 end는 캘린더의 시작일자와 종료일자 정보를 담고 있다.\r\n");
      out.write("\t\tevents: function(start, end, timezone, callback) {\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl:\"events.do\",\r\n");
      out.write("\t\t\t\tdata:{start:start.format(), end:end.format()},\r\n");
      out.write("\t\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\t\tsuccess:function(data) {\r\n");
      out.write("\t\t\t\t\t// data에는 해당 사용자의 일정정보들이 들어있다.\r\n");
      out.write("\t\t\t\t\t// data -> [{\"id\":1,\"title\":\"테스트\",\"start\":1490857200000,\"end\":1490860800000,\"description\":\"테스트\"}]\r\n");
      out.write("\t\t\t\t\t// 서버로부터 전달받은 데이터의 시작일/종료일이 time값이다.\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t// 일정들을 하나씩 순회하면서 start값과 end값을 날짜형식으로 변환한다.\r\n");
      out.write("\t\t\t\t\t// 1490857200000 -> 2017-03-25 09:00\r\n");
      out.write("\t\t\t\t\t$.each(data, function(index, item) {\r\n");
      out.write("\t\t\t\t\t\t// 타임값을 날짜형식의 문자열로 변환한다.\r\n");
      out.write("\t\t\t\t\t\titem.start = timeToString(item.start);\r\n");
      out.write("\t\t\t\t\t\titem.end = timeToString(item.end);\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t// 일정정보를 callback함수에 전달하고 callback함수를 실행한다.\r\n");
      out.write("\t\t\t\t\t// callback함수를 실행하면 캘린더가 갱신된다.\r\n");
      out.write("\t\t\t\t\tcallback(data);\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror:function() {\r\n");
      out.write("\t\t\t\t\talert(\"오류 발생\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\t// [eventClick : 캘린더에 표시된 일정 중 하나를 클릭했을 때 실행되는 콜백함수다.]\r\n");
      out.write("\t\teventClick: function(event, jsEvent, view) {\r\n");
      out.write("\t\t\tvar schNo = event[\"no\"]; \r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl:\"eventDetail.do\",\r\n");
      out.write("\t\t\t\tdata:'schNo=' + schNo,\r\n");
      out.write("\t\t\t\tdataType:\"json\",\r\n");
      out.write("\t\t\t\tsuccess:function(data) {\r\n");
      out.write("\t\t\t\t\t$(\"#event-title-detail\").val(data.title);\r\n");
      out.write("\t\t\t\t\t$(\"#event-description-detail\").val(data.description);\r\n");
      out.write("\t\t\t\t\t$(\"#event-no-detail\").val(data.no);\r\n");
      out.write("\t\t\t\t\t$(\"#event-start-date-detail\").val(timeToString(data.start).substring(0, 10));\r\n");
      out.write("\t\t\t\t\t$(\"#event-start-hour-detail\").val(timeToString(data.start).substring(11, 13));\r\n");
      out.write("\t\t\t\t\t$(\"#event-start-minute-detail\").val(timeToString(data.start).substring(14, 16));\r\n");
      out.write("\t\t\t\t\t$(\"#event-end-date-detail\").val(timeToString(data.end).substring(0, 10));\r\n");
      out.write("\t\t\t\t\t$(\"#event-end-hour-detail\").val(timeToString(data.end).substring(11, 13));\r\n");
      out.write("\t\t\t\t\t$(\"#event-end-minute-detail\").val(timeToString(data.end).substring(14, 16));\r\n");
      out.write("\t\t\t\t\t$(\"#event-form-modal-detail\").modal(\"show\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t},\t\r\n");
      out.write("\t\t// [dayClick : 캘린더의 날짜를 클릭했을 때 실행되는 콜백함수다.]\r\n");
      out.write("\t\tdayClick: function(date, jsEvent, view) {\r\n");
      out.write("\t\t\t// 일정정보를 입력하는 모달창의 입력값을 초기화한다.\r\n");
      out.write("\t\t\tinitializeForm(date);\r\n");
      out.write("\t\t\t// 모달창을 표시한다.\r\n");
      out.write("\t\t\t$(\"#event-form-modal\").modal(\"show\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("})\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>  \r\n");
      out.write(" <style type=\"text/css\">\r\n");
      out.write(" \r\n");
      out.write("@import url('//maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css');\r\n");
      out.write("\r\n");
      out.write(".navbar-default .navbar-nav #user-profile {\r\n");
      out.write("    height: 50px;\r\n");
      out.write("    padding-top: 15px;\r\n");
      out.write("    padding-left: 58px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-default .navbar-nav #user-profile img {\r\n");
      out.write("    height: 45px;\r\n");
      out.write("    width: 45px;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 2px;\r\n");
      out.write("    left: 8px;\r\n");
      out.write("    padding: 1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#wrapper {\r\n");
      out.write("    padding-top: 50px;\r\n");
      out.write("    padding-left: 0;\r\n");
      out.write("    -webkit-transition: all .5s ease;\r\n");
      out.write("    -moz-transition: all .5s ease;\r\n");
      out.write("    -o-transition: all .5s ease;\r\n");
      out.write("    transition: all .5s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media (min-width: 992px) {\r\n");
      out.write("    #wrapper {\r\n");
      out.write("        padding-left: 225px;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media (min-width: 992px) {\r\n");
      out.write("    #wrapper #sidebar-wrapper {\r\n");
      out.write("        width: 225px;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar-wrapper {\r\n");
      out.write("    border-right: 1px solid #e7e7e7;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar-wrapper {\r\n");
      out.write("    z-index: 1000;\r\n");
      out.write("    position: fixed;\r\n");
      out.write("    left: 225px;\r\n");
      out.write("    width: 0;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    margin-left: -225px;\r\n");
      out.write("    overflow-y: auto;\r\n");
      out.write("    background: #f8f8f8;\r\n");
      out.write("    -webkit-transition: all .5s ease;\r\n");
      out.write("    -moz-transition: all .5s ease;\r\n");
      out.write("    -o-transition: all .5s ease;\r\n");
      out.write("    transition: all .5s ease;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar-wrapper .sidebar-nav {\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    width: 225px;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    list-style: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar-wrapper .sidebar-nav li {\r\n");
      out.write("    text-indent: 0;\r\n");
      out.write("    line-height: 45px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar-wrapper .sidebar-nav li a {\r\n");
      out.write("    display: block;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar-wrapper .sidebar-nav li a .sidebar-icon {\r\n");
      out.write("    width: 45px;\r\n");
      out.write("    height: 45px;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    padding: 0 2px;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    text-indent: 7px;\r\n");
      out.write("    margin-right: 10px;\r\n");
      out.write("    color: #000;\r\n");
      out.write("    float: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar-wrapper .sidebar-nav li a .caret {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  right: 23px;\r\n");
      out.write("  top: auto;\r\n");
      out.write("  margin-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar-wrapper .sidebar-nav li ul.panel-collapse {\r\n");
      out.write("    list-style: none;\r\n");
      out.write("    -moz-padding-start: 0;\r\n");
      out.write("    -webkit-padding-start: 0;\r\n");
      out.write("    -khtml-padding-start: 0;\r\n");
      out.write("    -o-padding-start: 0;\r\n");
      out.write("    padding-start: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar-wrapper .sidebar-nav li ul.panel-collapse li i {\r\n");
      out.write("    margin-right: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#sidebar-wrapper .sidebar-nav li ul.panel-collapse li {\r\n");
      out.write("    text-indent: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media (max-width: 992px) {\r\n");
      out.write("    #wrapper #sidebar-wrapper {\r\n");
      out.write("        width: 45px;\r\n");
      out.write("    }\r\n");
      out.write("    #wrapper #sidebar-wrapper #sidebar #sidemenu li ul {\r\n");
      out.write("        position: fixed;\r\n");
      out.write("        left: 45px;\r\n");
      out.write("        margin-top: -45px;\r\n");
      out.write("        z-index: 1000;\r\n");
      out.write("        width: 200px;\r\n");
      out.write("        height: 0;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar-nav li a {\r\n");
      out.write("    color: #fff !important;\r\n");
      out.write("}\r\n");
      out.write(".sidebar-nav li ul li a {\r\n");
      out.write("\tbackground-color: #fff !important;\r\n");
      out.write("\tcolor: #0077e5 !important;\t\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("    <div id=\"navbar-wrapper\">\r\n");
      out.write("        <header>\r\n");
      out.write("            <nav class=\"navbar navbar-default navbar-fixed-top\" role=\"navigation\" style=\"background-color: #4296dc;\">            \r\n");
      out.write("                <div class=\"container-fluid\">\r\n");
      out.write("                    <div class=\"navbar-header\">\r\n");
      out.write("                        <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#navbar-collapse\">\r\n");
      out.write("                            <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("                            <span class=\"icon-bar\"></span>\r\n");
      out.write("                            <span class=\"icon-bar\"></span>\r\n");
      out.write("                            <span class=\"icon-bar\"></span>\r\n");
      out.write("                        </button>\r\n");
      out.write("                        <a class=\"navbar-brand\" href=\"home\" style=\"color: white;\"><span class=\"glyphicon glyphicon-education\"></span> JHTA 학사 관리 시스템</a>\r\n");
      out.write("                            <ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t\t      <li><a href=\"stuInfo\" style=\"color: white;\">학생 정보</a></li>\r\n");
      out.write("\t\t\t\t\t\t      <li><a href=\"#\" style=\"color: white;\">성적 조회</a></li>\r\n");
      out.write("\t\t\t\t\t\t      <li><a href=\"#\" style=\"color: white;\">학적 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t      <li><a href=\"#\" style=\"color: white;\">재학 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t      <li><a href=\"#\" style=\"color: white;\">과제 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t      <li><a href=\"#\" style=\"color: white;\">게시판</a></li>\r\n");
      out.write("    \t\t\t\t\t\t</ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    <div id=\"navbar-collapse\" class=\"collapse navbar-collapse\">\r\n");
      out.write("                        <ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("                        \t<li><a id=\"user-profile\" href=\"#\"style=\"color: white;\"><img src=\"\" class=\"img-responsive img-thumbnail img-circle\"> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${LOGIN_USER.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("님 환영합니다.</a></li>\r\n");
      out.write("                            <li><a href=\"#\" style=\"color: white;\">내 정보 수정</a></li>\r\n");
      out.write("                            <li><a href=\"/jhta/logout\" style=\"color: white;\">로그아웃</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </header>\r\n");
      out.write("    </div>\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function() {\r\n");
      out.write("\t$(\"a.accordion-toggle\").click(function() {\t\r\n");
      out.write("\t\t$(\".panel-collapse\").not($(this)).attr(\"class\",\"panel-collapse panel-switch collapse\");\r\n");
      out.write("\t});\r\n");
      out.write("})\r\n");
      out.write("</script>\r\n");
      out.write("\t<div id=\"wrapper\">\r\n");
      out.write("        <div id=\"sidebar-wrapper\">\r\n");
      out.write("            <aside id=\"sidebar\">\r\n");
      out.write("                <ul id=\"sidemenu\" class=\"sidebar-nav\" style=\"background-color: #4296dc;\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"accordion-toggle collapsed toggle-switch\" data-toggle=\"collapse\" data-target=\"#submenu-2\">\r\n");
      out.write("                            <span class=\"sidebar-icon\"></span><span class=\"sidebar-title\">학생 정보</span>\r\n");
      out.write("                            <b class=\"caret\"></b>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul id=\"submenu-2\" class=\"panel-collapse collapse panel-switch\" role=\"menu\">\r\n");
      out.write("                            <li><a href=\"stuInfo\"><i class=\"fa fa-caret-right\"></i>정보 조회</a></li>\r\n");
      out.write("                            <li><a href=\"stuPwdCheck\"><i class=\"fa fa-caret-right\"></i>비밀번호 변경</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"accordion-toggle collapsed toggle-switch\" data-toggle=\"collapse\" href=\"#submenu-3\">\r\n");
      out.write("                            <span class=\"sidebar-icon\"></span><span class=\"sidebar-title\">성적 조회</span>\r\n");
      out.write("                            <b class=\"caret\"></b>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul id=\"submenu-3\" class=\"panel-collapse collapse panel-switch\" role=\"menu\">\r\n");
      out.write("                            <li><a href=\"lookupScore\"><i class=\"fa fa-caret-right\"></i>현학기 성적 조회</a></li>\r\n");
      out.write("                            <li><a href=\"lookupAllScore\"><i class=\"fa fa-caret-right\"></i>전체학기 성적 조회</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"accordion-toggle collapsed toggle-switch\" data-toggle=\"collapse\" href=\"#submenu-4\">\r\n");
      out.write("                            <span class=\"sidebar-icon\"></span><span class=\"sidebar-title\">학적 관리</span>\r\n");
      out.write("                            <b class=\"caret\"></b>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul id=\"submenu-4\" class=\"panel-collapse collapse panel-switch\" role=\"menu\">\r\n");
      out.write("                            <li><a href=\"leave\"><i class=\"fa fa-caret-right\"></i>휴학 신청</a></li>\r\n");
      out.write("                            <li><a href=\"reinstate\"><i class=\"fa fa-caret-right\"></i>복학 신청</a></li>\r\n");
      out.write("                            <li><a href=\"#\"><i class=\"fa fa-caret-right\"></i>자퇴 신청</a></li>\r\n");
      out.write("                            <li><a href=\"#\"><i class=\"fa fa-caret-right\"></i>신청 조회 및 변경</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"accordion-toggle collapsed toggle-switch\" data-toggle=\"collapse\" href=\"#submenu-5\">\r\n");
      out.write("                            <span class=\"sidebar-icon\"></span><span class=\"sidebar-title\">재학 관리</span>                            <b class=\"caret\"></b>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul id=\"submenu-5\" class=\"panel-collapse collapse panel-switch\" role=\"menu\">\r\n");
      out.write("                            <li><a href=\"stuReport\"><i class=\"fa fa-caret-right\"></i>과제 관리</a></li>\r\n");
      out.write("                            <li><a href=\"#\"><i class=\"fa fa-caret-right\"></i>출결 관리</a></li>\r\n");
      out.write("                            <li><a href=\"studenttime\"><i class=\"fa fa-caret-right\"></i>시간표</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"accordion-toggle collapsed toggle-switch\" data-toggle=\"collapse\" href=\"#submenu-6\">\r\n");
      out.write("                            <span class=\"sidebar-icon\"></span><span class=\"sidebar-title\">수강 신청</span>\r\n");
      out.write("                            <b class=\"caret\"></b>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul id=\"submenu-6\" class=\"panel-collapse collapse panel-switch\" role=\"menu\">\r\n");
      out.write("                            <li><a href=\"enrollMain\"><i class=\"fa fa-caret-right\"></i>수강 신청</a></li>\r\n");
      out.write("                            <li><a href=\"nowEnrollList\"><i class=\"fa fa-caret-right\"></i>수강 목록</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"accordion-toggle collapsed toggle-switch\" data-toggle=\"collapse\" href=\"#submenu-7\">\r\n");
      out.write("                            <span class=\"sidebar-icon\"></span><span class=\"sidebar-title\">게시판</span>\r\n");
      out.write("                            <b class=\"caret\"></b>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul id=\"submenu-7\" class=\"panel-collapse collapse panel-switch\" role=\"menu\">\r\n");
      out.write("                            <li><a href=\"studeptboard\"><i class=\"fa fa-caret-right\"></i>학과 게시판</a></li>\r\n");
      out.write("                            <li><a href=\"stufreeboard\"><i class=\"fa fa-caret-right\"></i>자유 게시판</a></li>\r\n");
      out.write("                            <li><a href=\"stuqnaboard\"><i class=\"fa fa-caret-right\"></i>Q&amp;A 게시판</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"accordion-toggle collapsed toggle-switch\" data-toggle=\"collapse\" href=\"#submenu-8\">\r\n");
      out.write("                            <span class=\"sidebar-icon\"></span><span class=\"sidebar-title\">검색</span>\r\n");
      out.write("                            <b class=\"caret\"></b>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul id=\"submenu-8\" class=\"panel-collapse collapse panel-switch\" role=\"menu\">\r\n");
      out.write("                            <li><a href=\"#\"><i class=\"fa fa-caret-right\"></i>논문 검색</a></li>\r\n");
      out.write("                            <li><a href=\"#\"><i class=\"fa fa-caret-right\"></i>도서 검색</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a class=\"accordion-toggle collapsed toggle-switch\" data-toggle=\"collapse\" href=\"#submenu-8\">\r\n");
      out.write("                            <span class=\"sidebar-icon\"></span><span class=\"sidebar-title\">기타 관리</span>\r\n");
      out.write("                            <b class=\"caret\"></b>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul id=\"submenu-8\" class=\"panel-collapse collapse panel-switch\" role=\"menu\">\r\n");
      out.write("                            <li><a href=\"#\"><i class=\"fa fa-caret-right\"></i>기타1</a></li>\r\n");
      out.write("                            <li><a href=\"#\"><i class=\"fa fa-caret-right\"></i>기타2</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </aside>            \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>");
      out.write("\r\n");
      out.write("\t<div class=\"container\" style=\"margin-left: 250px; padding-top:25px; \">\r\n");
      out.write("    <div class=\"row text-right\">\r\n");
      out.write("         홈\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("         <h4><span class=\"glyphicon glyphicon-th-list\"></span> HOME</h4>\r\n");
      out.write("         <hr style=\"border:solid 0.5px #2C7BB5;\">\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("\t      <div class=\"col-xs-6\">\r\n");
      out.write("\t      \t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t      \t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t<strong>최근 공지사항</strong>\r\n");
      out.write("\t\t        </div> \r\n");
      out.write("\t\t       \t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t<table class=\"table table-default\">\r\n");
      out.write("\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"*%\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"15%\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"20%\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"15%\">\r\n");
      out.write("\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>번호</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>제목</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>작성자</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>작성일</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>조회수</th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t      \t</div>\r\n");
      out.write("\t      \t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t      \t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t<strong>학과 게시판</strong><div class=\"pull-right\"><span style=\"padding-left: 5px;\"><a href=\"studeptboard\" class=\"btn-default btn-xs\">more</a></span></div>\r\n");
      out.write("\t\t        </div> \r\n");
      out.write("\t\t       \t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t<table class=\"table table-default\">\r\n");
      out.write("\t\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"10%\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"*%\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"15%\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"20%\">\r\n");
      out.write("\t\t\t\t\t\t\t<col width=\"15%\">\r\n");
      out.write("\t\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>번호</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>제목</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>작성자</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>작성일</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>조회수</th>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("\t      \t</div>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t      \r\n");
      out.write("\t      <div class=\"col-xs-6\">\r\n");
      out.write("\t      \t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t      \t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t<strong>일정</strong>\r\n");
      out.write("\t\t        </div> \r\n");
      out.write("\t\t       \t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t\t\t<div id=\"calendar-box\"></div>\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("      \t\t</div>\r\n");
      out.write("\t      \t<div class=\"panel panel-default\">\r\n");
      out.write("\t\t      \t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t\t\t<strong>추가</strong><span style=\"padding-left: 5px;\"><a href=\"\" class=\"btn-default btn-xs\">more</a></span>\r\n");
      out.write("\t\t        </div> \r\n");
      out.write("\t\t       \t<div class=\"panel-body\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t        </div>\r\n");
      out.write("      \t\t</div>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t      <div class=\"row\">\r\n");
      out.write("\t      \t<div class=\"col-xs-1\"></div>\r\n");
      out.write("\t      \t<div class=\"col-xs-10\">\r\n");
      out.write("\t\t      \t<table class=\"table table-bordered\">\r\n");
      out.write("\t\t      \t\t<colgroup>\r\n");
      out.write("\t\t      \t\t\t<col width=\"10%\" />\r\n");
      out.write("\t\t      \t\t\t<col width=\"10%\" />\r\n");
      out.write("\t\t      \t\t\t<col width=\"*\" />\r\n");
      out.write("\t\t      \t\t\t<col width=\"10%\" />\r\n");
      out.write("\t\t      \t\t\t<col width=\"10%\" />\r\n");
      out.write("\t\t      \t\t\t<col width=\"10%\" />\r\n");
      out.write("\t\t      \t\t</colgroup>\r\n");
      out.write("\t\t      \t\t<thead>\r\n");
      out.write("\t\t      \t\t\t<tr>\r\n");
      out.write("\t\t      \t\t\t\t<th>학기</th>\r\n");
      out.write("\t\t      \t\t\t\t<th>강좌구분</th>\r\n");
      out.write("\t\t      \t\t\t\t<th>교과목명</th>\r\n");
      out.write("\t\t      \t\t\t\t<th>교수</th>\r\n");
      out.write("\t\t      \t\t\t\t<th>조회</th>\r\n");
      out.write("\t\t      \t\t\t</tr>\r\n");
      out.write("\t\t      \t\t</thead>\r\n");
      out.write("\t\t      \t\t<tbody>\r\n");
      out.write("\t\t      \t\t\t<tr>\r\n");
      out.write("\t\t      \t\t\t\t<th></th>\r\n");
      out.write("\t\t      \t\t\t\t<th></th>\r\n");
      out.write("\t\t      \t\t\t\t<th></th>\r\n");
      out.write("\t\t      \t\t\t\t<th></th>\r\n");
      out.write("\t\t      \t\t\t\t<th></th>\r\n");
      out.write("\t\t      \t\t\t</tr>\r\n");
      out.write("\t\t      \t\t</tbody>\r\n");
      out.write("\t\t      \t</table>\r\n");
      out.write("\t      \t</div>\r\n");
      out.write("\t      \t<div class=\"col-xs-1\"></div>\r\n");
      out.write("\t      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("   <!-- 모달 -->\r\n");
      out.write("   <div class=\"modal fade\" id=\"event-form-modal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"gridSystemModalLabel\">\r\n");
      out.write("  \t\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("    \t\t<div class=\"modal-content\">\r\n");
      out.write("      \t\t\t<div class=\"modal-header\">\r\n");
      out.write("        \t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>\r\n");
      out.write("        \t\t\t<h4 class=\"modal-title\" id=\"gridSystemModalLabel\">새 일정 등록폼</h4>\r\n");
      out.write("      \t\t\t</div>\r\n");
      out.write("      \t\t\t<div class=\"modal-body\">\r\n");
      out.write("      \t\t\t\t<form class=\"form-horizontal well\">\r\n");
      out.write("  \t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("    \t\t\t\t\t\t<label for=\"title\" class=\"col-sm-2 control-label\">제목</label>\r\n");
      out.write("    \t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("      \t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"event-title\" name=\"title\" placeholder=\"제목을 입력하세요\">\r\n");
      out.write("    \t\t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("    \t\t\t\t\t\t<label for=\"description\" class=\"col-sm-2 control-label\">내용</label>\r\n");
      out.write("    \t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("      \t\t\t\t\t\t\t<textarea rows=\"3\" class=\"form-control\" id=\"event-description\" name=\"description\" placeholder=\"내용을 입력하세요\" ></textarea>\r\n");
      out.write("    \t\t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("    \t\t\t\t\t\t<label for=\"start-date\" class=\"col-sm-2 control-label\">시작 일시</label>\r\n");
      out.write("    \t\t\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("      \t\t\t\t\t\t\t<input type=\"date\" class=\"form-control\" id=\"event-start-date\" name=\"startDate\" >\r\n");
      out.write("    \t\t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t\t<div class=\"col-sm-2\">\r\n");
      out.write("      \t\t\t\t\t\t\t<input type=\"number\" class=\"form-control\" id=\"event-start-hour\" name=\"startHour\"  min=\"0\" max=\"23\" step=\"1\">\r\n");
      out.write("    \t\t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t\t<label for=\"start-hour\" class=\"col-sm-1 control-label\">시</label>\r\n");
      out.write("    \t\t\t\t\t\t<div class=\"col-sm-2\">\r\n");
      out.write("      \t\t\t\t\t\t\t<input type=\"number\" class=\"form-control\" id=\"event-start-minute\" name=\"startMinute\"  min=\"00\" max=\"50\" step=\"10\">\r\n");
      out.write("    \t\t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t\t<label for=\"start-minute\" class=\"col-sm-1 control-label\">분</label>\r\n");
      out.write("  \t\t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("    \t\t\t\t\t\t<label for=\"end-date\" class=\"col-sm-2 control-label\">종료 일시</label>\r\n");
      out.write("    \t\t\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("      \t\t\t\t\t\t\t<input type=\"date\" class=\"form-control\" id=\"event-end-date\" name=\"endDate\" >\r\n");
      out.write("    \t\t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t\t<div class=\"col-sm-2\">\r\n");
      out.write("      \t\t\t\t\t\t\t<input type=\"number\" class=\"form-control\" id=\"event-end-hour\" name=\"endHour\" min=\"0\" max=\"23\" step=\"1\">\r\n");
      out.write("    \t\t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t\t<label for=\"end-hour\" class=\"col-sm-1 control-label\">시</label>\r\n");
      out.write("    \t\t\t\t\t\t<div class=\"col-sm-2\">\r\n");
      out.write("      \t\t\t\t\t\t\t<input type=\"number\" class=\"form-control\" id=\"event-end-minute\" name=\"endMinute\" min=\"00\" max=\"50\" step=\"10\" >\r\n");
      out.write("    \t\t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t\t<label for=\"end-minute\" class=\"col-sm-1 control-label\">분</label>\r\n");
      out.write("  \t\t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("    \t\t\t\t\t\t<label for=\"title\" class=\"col-sm-2 control-label\">하루 종일</label>\r\n");
      out.write("    \t\t\t\t\t\t<div class=\"col-sm-1\">\r\n");
      out.write("    \t\t\t\t\t\t\t<input type=\"checkbox\" class=\"form-control\" id=\"event-all-day\" name=\"allDay\">\r\n");
      out.write("    \t\t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("      \t\t\t</div>\r\n");
      out.write("      \t\t\t<div class=\"modal-footer\">\r\n");
      out.write("        \t\t\t<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">닫기</button>\r\n");
      out.write("        \t\t\t<button type=\"button\" class=\"btn btn-primary\" id=\"add-event-btn\">등록</button>\r\n");
      out.write("      \t\t\t</div>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("   <div class=\"modal fade\" id=\"event-form-modal-detail\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"gridSystemModalLabel\">\r\n");
      out.write("  \t\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("    \t\t<div class=\"modal-content\">\r\n");
      out.write("      \t\t\t<div class=\"modal-header\">\r\n");
      out.write("        \t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\"><span aria-hidden=\"true\">&times;</span></button>\r\n");
      out.write("        \t\t\t<h4 class=\"modal-title\" id=\"gridSystemModalLabel\">일정 조회</h4>\r\n");
      out.write("        \t\t\t<input type=\"hidden\" id=\"event-no-detail\" value=\"\"/>\r\n");
      out.write("      \t\t\t</div>\r\n");
      out.write("      \t\t\t<div class=\"modal-body\">\r\n");
      out.write("      \t\t\t\t<form class=\"form-horizontal well\">\r\n");
      out.write("  \t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("    \t\t\t\t\t\t<label for=\"title\" class=\"col-sm-2 control-label\">제목</label>\r\n");
      out.write("    \t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("      \t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"event-title-detail\" name=\"title\" placeholder=\"제목을 입력하세요\">\r\n");
      out.write("    \t\t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("    \t\t\t\t\t\t<label for=\"description\" class=\"col-sm-2 control-label\">내용</label>\r\n");
      out.write("    \t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("      \t\t\t\t\t\t\t<textarea rows=\"3\" class=\"form-control\" id=\"event-description-detail\" name=\"description\" placeholder=\"내용을 입력하세요\" ></textarea>\r\n");
      out.write("    \t\t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("    \t\t\t\t\t\t<label for=\"start-date\" class=\"col-sm-2 control-label\">시작 일시</label>\r\n");
      out.write("    \t\t\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("      \t\t\t\t\t\t\t<input type=\"date\" class=\"form-control\" id=\"event-start-date-detail\" name=\"startDate\" >\r\n");
      out.write("    \t\t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t\t<div class=\"col-sm-2\">\r\n");
      out.write("      \t\t\t\t\t\t\t<input type=\"number\" class=\"form-control\" id=\"event-start-hour-detail\" name=\"startHour\"  min=\"0\" max=\"23\" step=\"1\">\r\n");
      out.write("    \t\t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t\t<label for=\"start-hour\" class=\"col-sm-1 control-label\">시</label>\r\n");
      out.write("    \t\t\t\t\t\t<div class=\"col-sm-2\">\r\n");
      out.write("      \t\t\t\t\t\t\t<input type=\"number\" class=\"form-control\" id=\"event-start-minute-detail\" name=\"startMinute\"  min=\"00\" max=\"50\" step=\"10\">\r\n");
      out.write("    \t\t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t\t<label for=\"start-minute\" class=\"col-sm-1 control-label\">분</label>\r\n");
      out.write("  \t\t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("    \t\t\t\t\t\t<label for=\"end-date\" class=\"col-sm-2 control-label\">종료 일시</label>\r\n");
      out.write("    \t\t\t\t\t\t<div class=\"col-sm-4\">\r\n");
      out.write("      \t\t\t\t\t\t\t<input type=\"date\" class=\"form-control\" id=\"event-end-date-detail\" name=\"endDate\" >\r\n");
      out.write("    \t\t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t\t<div class=\"col-sm-2\">\r\n");
      out.write("      \t\t\t\t\t\t\t<input type=\"number\" class=\"form-control\" id=\"event-end-hour-detail\" name=\"endHour\" min=\"0\" max=\"23\" step=\"1\">\r\n");
      out.write("    \t\t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t\t<label for=\"end-hour\" class=\"col-sm-1 control-label\">시</label>\r\n");
      out.write("    \t\t\t\t\t\t<div class=\"col-sm-2\">\r\n");
      out.write("      \t\t\t\t\t\t\t<input type=\"number\" class=\"form-control\" id=\"event-end-minute-detail\" name=\"endMinute\" min=\"00\" max=\"50\" step=\"10\" >\r\n");
      out.write("    \t\t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t\t<label for=\"end-minute\" class=\"col-sm-1 control-label\">분</label>\r\n");
      out.write("  \t\t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("    \t\t\t\t\t\t<label for=\"title\" class=\"col-sm-2 control-label\">하루 종일</label>\r\n");
      out.write("    \t\t\t\t\t\t<div class=\"col-sm-1\">\r\n");
      out.write("    \t\t\t\t\t\t\t<input type=\"checkbox\" class=\"form-control\" id=\"event-all-day-detail\" name=\"allDay\">\r\n");
      out.write("    \t\t\t\t\t\t</div>\r\n");
      out.write("  \t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("      \t\t\t</div>\r\n");
      out.write("      \t\t\t<div class=\"modal-footer\">\r\n");
      out.write("        \t\t\t<button type=\"button\" class=\"btn btn-primary\" id=\"edit-event-btn\">수정</button>\r\n");
      out.write("        \t\t\t<button type=\"button\" class=\"btn btn-danger\" id=\"delete-event-btn\">삭제</button>\r\n");
      out.write("        \t\t\t<button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">닫기</button>\r\n");
      out.write("      \t\t\t</div>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("  \t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/student/stuMain.jsp(232,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("board");
      // /WEB-INF/views/student/stuMain.jsp(232,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/student/stuMain.jsp(232,7) '${boardList }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${boardList }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td><a href=\"stuNoticeBoarddetail?bno=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.writer }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>");
            if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write(" </td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.countView }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    try {
      _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/student/stuMain.jsp(237,13) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.regdate }", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/views/student/stuMain.jsp(268,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("board");
      // /WEB-INF/views/student/stuMain.jsp(268,7) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/student/stuMain.jsp(268,7) '${deptList }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${deptList }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td><a href=\"stuDeptBoarddetail?bno=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.no }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.writer }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>");
            if (_jspx_meth_fmt_005fformatDate_005f1(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write(" </td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.countView }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    try {
      _jspx_th_fmt_005fformatDate_005f1.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /WEB-INF/views/student/stuMain.jsp(273,13) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f1.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board.regdate }", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_fmt_005fformatDate_005f1 = _jspx_th_fmt_005fformatDate_005f1.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f1);
    }
    return false;
  }
}
